import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import Counter from 'ui/Counter';
import Layout from 'ui/Layout';

const Server: NextPage = () => {

  // const [myCount, setMyCount] = useState(0);

  return (
    <>
      <Head>
        <title>Server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <h1>
            Server
          </h1>
          <br />
          {/* <Counter count={myCount} onIncrement={() => setMyCount(myCount + 1)} onDecrement={() => setMyCount(myCount - 1)} /> */}
          <br />
          <Link href="/" >
            <a>Home</a>
          </Link>
          <Link href="/login" >
            <a>Login</a>
          </Link>
          <Link href="/ui" >
            <a>UI</a>
          </Link>
        </Layout>
      </main>
    </>
  )
}

Server.getInitialProps = async (ctx) => {
  return {};
}

export default Server
